webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    # Mode strict : lève une exception si un fichier n'est pas dans le manifest
    strict_mode: false
    crossorigin: 'anonymous'
    script_attributes:
        defer: true
    preload: true
